# Generated by Django 5.0.7 on 2024-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questionBank',
            fields=[
                ('qID', models.IntegerField(primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=255)),
                ('op1', models.CharField(max_length=255)),
                ('op2', models.CharField(max_length=255)),
                ('op3', models.CharField(max_length=255)),
                ('op4', models.CharField(max_length=255)),
                ('CorrectAnswer', models.CharField(max_length=255)),
                ('option_number', models.IntegerField()),
                ('difficulty', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
            ],
        ),
    ]
