# Generated by Django 5.1.1 on 2024-09-22 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='questionBank',
            fields=[
                ('qID', models.IntegerField(primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=255)),
                ('op1', models.CharField(max_length=255)),
                ('op2', models.CharField(max_length=255)),
                ('op3', models.CharField(max_length=255)),
                ('op4', models.CharField(max_length=255)),
                ('CorrectAnswer', models.CharField(max_length=255)),
                ('option_number', models.IntegerField()),
                ('difficulty', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpID', models.IntegerField()),
                ('qID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queID', to='eva01.questionbank')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('marked_for_review', models.IntegerField()),
                ('time_taken', models.IntegerField()),
                ('qID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionID', to='eva01.questionbank')),
                ('qpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionPaperID', to='eva01.questionpapers')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('selected_subjects', models.ManyToManyField(blank=True, to='eva01.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
