# Generated by Django 5.1 on 2024-08-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eva01', '0002_userattempts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userAttempts',
        ),
    ]
