# Generated by Django 5.1 on 2024-08-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva01', '0004_userattempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpID', models.IntegerField()),
                ('qID', models.IntegerField()),
            ],
        ),
    ]
