# Generated by Django 5.1 on 2024-08-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eva01', '0006_userattempts_qpid_alter_userattempts_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userAttempts',
        ),
    ]
