# Generated by Django 5.1 on 2024-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva01', '0007_delete_userattempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpID', models.IntegerField()),
                ('qID', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('marked_for_review', models.IntegerField()),
                ('time_taken', models.IntegerField()),
            ],
        ),
    ]
